version: "3.9"
services:
  wordpress:
    image: wordpress:6.5-php8.1-apache
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html/wp-content/plugins
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
      WORDPRESS_DB_NAME: wp
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  vue:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/frontend/src
      - ./frontend/index.html:/frontend/index.html
      - ./frontend/main.js:/frontend/main.js
      - ./frontend/vite.config.js:/frontend/vite.config.js
      - ./frontend/package.json:/frontend/package.json
    working_dir: /frontend
    command: npm run dev
    depends_on:
      - wordpress

volumes:
  db_data:
